Traceback (most recent call last):
  File "C:\Users\FIKRI\AppData\Local\Programs\Python\Python311\Lib\site-packages\jupyter_core\utils\__init__.py", line 154, in wrapped
    asyncio.get_running_loop()
RuntimeError: no running event loop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\FIKRI\AppData\Local\Programs\Python\Python311\Lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\FIKRI\AppData\Local\Programs\Python\Python311\Lib\site-packages\nbclient\client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FIKRI\AppData\Local\Programs\Python\Python311\Lib\site-packages\jupyter_core\utils\__init__.py", line 158, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FIKRI\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\FIKRI\AppData\Local\Programs\Python\Python311\Lib\site-packages\nbclient\client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "C:\Users\FIKRI\AppData\Local\Programs\Python\Python311\Lib\site-packages\nbclient\client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\FIKRI\AppData\Local\Programs\Python\Python311\Lib\site-packages\nbclient\client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import pandas as pd
from sqlalchemy import create_engine

# Konfigurasi koneksi PostgreSQL
username = "postgres"password = "admin"   
host = "localhost"         
port = "5432"              
database = "postgres"      

# Buat koneksi ke PostgreSQL
engine = create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")

# Ambil daftar semua tabel di schema public
tables = pd.read_sql("""
    SELECT table_name 
    FROM information_schema.tables 
    WHERE table_schema = 'public'
""", engine)

# Dictionary untuk simpan semua tabel sebagai DataFrame
dataframes = {}

# Loop tiap tabel dan load ke pandas
for table in tables['table_name']:
    query = f'SELECT * FROM public."{table}";'
    dataframes[table] = pd.read_sql(query, engine)

# Contoh akses: tampilkan 5 data teratas dari coffe_sales
print(dataframes['coffe_sales'].head())

------------------


  [36mCell[39m[36m [39m[32mIn[1][39m[32m, line 5[39m
[31m    [39m[31musername = "postgres"password = "admin"[39m
                         ^
[31mSyntaxError[39m[31m:[39m invalid syntax


